//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Ivanov_Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Password { get; set; }
        public string Login { get; set; }
        public string Image { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patrronymic { get; set; }
    }
}
