//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Ivanov_Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes_in_Order
    {
        public int id_dishes_in_order { get; set; }
        public int id_order { get; set; }
        public int id_dish { get; set; }
        public int Quantity { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Order Order { get; set; }
    }
}
