//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Ivanov_Admin.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_of_dishes> Category_of_dishes { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Dishes_in_Order> Dishes_in_Order { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orders_in_payment> Orders_in_payment { get; set; }
        public virtual DbSet<Payment_for_orders> Payment_for_orders { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Position> Position { get; set; }
    }
}
