//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Ivanov_Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_in_payment
    {
        public int id_orders_in_payment { get; set; }
        public int id_order { get; set; }
        public int id_payment { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Payment_for_orders Payment_for_orders { get; set; }
    }
}
