//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Ivanov_Admin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_for_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment_for_orders()
        {
            this.Orders_in_payment = new HashSet<Orders_in_payment>();
        }
    
        public int id_payment { get; set; }
        public int Amount_of_orders { get; set; }
        public int Paid { get; set; }
        public int Change { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_in_payment> Orders_in_payment { get; set; }
    }
}
